---
name: Lint and static check codes

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11-dev"
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Flake8
        run: flake8 pylogcounter

      - name: Black
        run: black pylogcounter --line-length 120

      - name: Mypy
        run: mypy pylogcounter

      - name: Pytest
        run: pytest
