name: Build and push docker image

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract package version
        id: vars
        run: echo "version=${{ github.ref_name }}" | sed "s/v//" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          build-args: |
            version=${{ steps.vars.outputs.version }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pylogcounter:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pylogcounter:${{ steps.vars.outputs.version }}
