name: publish python package

env:
  PYTHON_VERSION: 3.x

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    name: Build and push Python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Python dependencies
        run: pip install --upgrade build twine

      - name: Build Python package
        run: python -m build

      - name: Publish Python package
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload --disable-progress-bar -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*
